#!/bin/bash
git_add_changed_to_index() {
    git diff --name-only --cached | xargs git add
}

changed_files=$(git diff --diff-filter=ACMR --name-only --cached --relative)

kt_files=$(echo "$changed_files" | grep '\.kt[s"]\?$')
if command -v ktlint > /dev/null 2>&1 && [[ -n $kt_files ]]; then
    echo "Running ktlint formatter..."

    if ! ktlint -F --relative . "$kt_files"; then exit 1; fi

    git_add_changed_to_index
fi

tf_files=$(echo "$changed_files" | grep '\.tf\?$')
if command -v terraform > /dev/null 2>&1 && [[ -n $tf_files ]]; then
    echo "Running terraform fmt..."

    for file in ${tf_files}; do
        if ! terraform fmt "$file"; then exit 1; fi
    done

    git_add_changed_to_index
fi

go_files=$(echo "$changed_files" | grep '\.go\?$')
if command -v go > /dev/null 2>&1 && [[ -n $go_files ]]; then
    echo "Running go fmt..."

    for file in ${go_files}; do
        if ! go fmt "$file"; then exit 1; fi
    done

    git_add_changed_to_index
fi

exit 0
